/* Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
 2 ^ 2 = 4 ... 5 ^ 5 = 3125
If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 */

using System;
using System.Collections.Generic;
using System.Linq;
using Shared;

namespace pn29
{
    class Program
    {
        const int START = 2;
        const int END = 101;
        const int COUNT = END - START;

        static void Main(string[] args)
        {
            int result = CombinationOfPowers(START, COUNT).Count();

            Console.WriteLine(result);
        }

        private static IEnumerable<double> CombinationOfPowers(int start, int count) =>
            Enumerable.Range(start, count)
            .SelectMany(n => Enumerable.Range(start, count).Select(p => n.Pow(p)))
            .Distinct();
    }
}
